## Model settings
BASE_MAX_TOKENS_CODE: 120
BASE_MAX_TOKENS_SUM: 160
MAX_TOKENS_CODE: 90
MAX_TOKENS_SUM: 160
MAX_TOKENS_CHAIN: 512
TEMPERATURE: 0.1
CONTEXT_WINDOW: 120000
CHUNK_SIZE: 120000
MODEL_TYPE: "chat"
MODEL_NAME: "gpt-3.5-turbo-instruct"
MODEL_CHAT_NAME: "gpt-4-turbo"

## File paths
DIRECTORY_PATH: "C:/Users/jeelb/OneDrive - Stichting ICTU/Documenten/Code genAI/quality-time/components/notifier/src/notifier/notifier.py"

JSON_FILE_NAME: "metrics/summary_quality-time_GPT4.json"
JSON_EXPERIMENT_NAME: "summaries_settings_GTP4-turbo0125-100-130-1shot" #format: summaries_settings_MODELVERSION-CODE_TOKENS-SUM_TOKENS
HTML_FILE_NAME: "metrics/summary_quality-time_GPT4.html"

ARCHITECTURE_DOC: "example_files/ICTU-Template-Software-architectuurdocument.docx"
ARCHITECTURE_JSON: "metrics/architecture_quality-time_GPT4.json"