MAX_TOKENS: 128
MAX_TOKENS_CHAIN: 512
TEMPERATURE: 0
DIRECTORY_PATH: "C:/Users/jeelb/OneDrive - Stichting ICTU/Documenten/Code genAI/quality-time/components/notifier/src/notifier/notifier.py"
MODEL_TYPE: "completion"
MODEL_NAME: "gpt-3.5-turbo-instruct"
MODEL_CHAT_NAME: "gpt-3.5-turbo-1106"
JSON_FILE_NAME: "metrics/summaries.json"
JSON_EXPERIMENT_NAME: "summaries_settings_GPT3.5-128" #format: summaries_settings_MODELVERSION-MAX_TOKENS
CONTEXT_WINDOW: 4000
CHUNK_SIZE: 2000