MAX_TOKENS: 128
TEMPERATURE: 0
DIRECTORY_PATH: "C:/Users/jeelb/OneDrive - Stichting ICTU/Documenten/Code genAI/quality-time/components/collector/"
MODEL_NAME: "gpt-3.5-turbo-instruct"
JSON_FILE_NAME: "metrics/example-metrics.json"
JSON_EXPERIMENT_NAME: "experiment1_summarization"



#LOG_FILE: 'log_loaded.txt'
#EMBEDDINGS_MODEL_NAME: 'sentence-transformers/all-MiniLM-L12-v2' 
#TOKENIZER: "OPENAI"